In [1]:
import pandas as pd

In [2]:
crime = pd.read_csv("Crime_Data_from_2020_to_Present.csv")

In [7]:
crime

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,10304468,01/08/2020 12:00:00 AM,01/08/2020 12:00:00 AM,2230,3,Southwest,377,2,624,BATTERY - SIMPLE ASSAULT,...,AO,Adult Other,624.0,NaN,NaN,NaN,1100 W 39TH PL,NaN,34.0141,-118.2978
1,190101086,01/02/2020 12:00:00 AM,01/01/2020 12:00:00 AM,330,1,Central,163,2,624,BATTERY - SIMPLE ASSAULT,...,IC,Invest Cont,624.0,NaN,NaN,NaN,700 S HILL ST,NaN,34.0459,-118.2545
2,200110444,04/14/2020 12:00:00 AM,02/13/2020 12:00:00 AM,1200,1,Central,155,2,845,SEX OFFENDER REGISTRANT OUT OF COMPLIANCE,...,AA,Adult Arrest,845.0,NaN,NaN,NaN,200 E 6TH ST,NaN,34.0448,-118.2474
3,191501505,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,1730,15,N Hollywood,1543,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745.0,998.0,NaN,NaN,5400 CORTEEN PL,NaN,34.1685,-118.4019
4,191921269,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,415,19,Mission,1998,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,14400 TITUS ST,NaN,34.2198,-118.4468
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
559614,221213384,06/07/2022 12:00:00 AM,06/07/2022 12:00:00 AM,1900,12,77th Street,1249,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,AO,Adult Other,626.0,NaN,NaN,NaN,6600 S HOOVER ST,NaN,33.9792,-118.2871
559615,220314584,08/02/2022 12:00:00 AM,08/02/2022 12:00:00 AM,10,3,Southwest,334,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,4300 W 28TH ST,NaN,34.0311,-118.3335
559616,221005507,02/10/2022 12:00:00 AM,02/09/2022 12:00:00 AM,1530,10,West Valley,1024,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,18800 SHERMAN WY,NaN,34.2011,-118.5426
559617,221105477,02/10/2022 12:00:00 AM,02/08/2022 12:00:00 AM,2000,11,Northeast,1171,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,4000 FOUNTAIN AV,NaN,34.0958,-118.2787
559618,221605448,02/15/2022 12:00:00 AM,02/14/2022 12:00:00 AM,1800,16,Foothill,1613,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,IC,Invest Cont,331.0,NaN,NaN,NaN,12700 VAN NUYS BL,NaN,34.2755,-118.4092

In [8]:
crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 559619 entries, 0 to 559618
Data columns (total 28 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   DR_NO           559619 non-null  int64
 1   Date Rptd       559619 non-null  object
 2   DATE OCC        559619 non-null  object
 3   TIME OCC        559619 non-null  int64
 4   AREA            559619 non-null  int64
 5   AREA NAME       559619 non-null  object
 6   Rpt Dist No     559619 non-null  int64
 7   Part 1-2        559619 non-null  int64
 8   Crm Cd          559619 non-null  int64
 9   Crm Cd Desc     559619 non-null  object
 10  Mocodes         482136 non-null  object
 11  Vict Age        559619 non-null  int64
 12  Vict Sex        485536 non-null  object
 13  Vict Descent    485531 non-null  object
 14  Premis Cd       559614 non-null  float64
 15  Premis Desc     559362 non-null  object
 16  Weapon Used Cd  198770 non-null  float64
 17  Weapon Desc     198770 non-null  object
 18  Status          559619 non-null  object
 19  Status Desc     559619 non-null  object
 20  Crm Cd 1        559613 non-null  float64
 21  Crm Cd 2        42971 non-null   float64
 22  Crm Cd 3        1458 non-null    float64
 23  Crm Cd 4        41 non-null      float64
 24  LOCATION        559619 non-null  object
 25  Cross Street    94673 non-null   object
 26  LAT             559619 non-null  float64
 27  LON             559619 non-null  float64
dtypes: float64(8), int64(7), object(13)
memory usage: 119.5+ MB

In [12]:
crimes = crime["Crm Cd Desc"]
locations = crime["LOCATION"]

In [16]:
crime[locations.str.contains("ROSSMORE")]

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
5261,200700649,04/04/2020 12:00:00 AM,04/03/2020 12:00:00 AM,2300,7,Wilshire,719,1,440,THEFT PLAIN - PETTY ($950 & UNDER),...,IC,Invest Cont,440.0,998.0,NaN,NaN,300 N ROSSMORE AV,NaN,34.0761,-118.3272
5432,200714937,10/15/2020 12:00:00 AM,10/09/2020 12:00:00 AM,1700,7,Wilshire,719,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,IC,Invest Cont,331.0,NaN,NaN,NaN,500 N ROSSMORE AV,NaN,34.0790,-118.3273
7861,200707611,03/07/2020 12:00:00 AM,03/07/2020 12:00:00 AM,200,7,Wilshire,719,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,600 N ROSSMORE AV,NaN,34.0817,-118.3272
8915,200710419,06/13/2020 12:00:00 AM,06/13/2020 12:00:00 AM,930,7,Wilshire,719,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,ROSSMORE,ARDEN BL,34.0835,-118.3266
8952,200715015,10/17/2020 12:00:00 AM,10/17/2020 12:00:00 AM,1900,7,Wilshire,719,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,600 N ROSSMORE AV,NaN,34.0817,-118.3272
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547451,220712114,07/26/2022 12:00:00 AM,07/19/2022 12:00:00 AM,1300,7,Wilshire,719,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,NaN,NaN,NaN,300 N ROSSMORE AV,NaN,34.0761,-118.3272
547834,220707185,03/25/2022 12:00:00 AM,03/24/2022 12:00:00 AM,1710,7,Wilshire,719,2,624,BATTERY - SIMPLE ASSAULT,...,IC,Invest Cont,624.0,NaN,NaN,NaN,500 N ROSSMORE AV,NaN,34.0790,-118.3273
553166,220708119,04/15/2022 12:00:00 AM,04/14/2022 12:00:00 AM,1240,7,Wilshire,719,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,NaN,NaN,NaN,600 N ROSSMORE AV,NaN,34.0817,-118.3272
554685,220707103,03/22/2022 12:00:00 AM,03/18/2022 12:00:00 AM,2355,7,Wilshire,719,1,121,"RAPE, FORCIBLE",...,IC,Invest Cont,121.0,NaN,NaN,NaN,500 N ROSSMORE AV,NaN,34.0790,-118.3273
556616,220708460,04/26/2022 12:00:00 AM,04/25/2022 12:00:00 AM,2100,7,Wilshire,719,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,NaN,NaN,NaN,500 N ROSSMORE AV,NaN,34.0790,-118.3273

In [17]:
rossmore_crimes = crime[locations.str.contains("ROSSMORE")]["Crm Cd Desc"]

In [20]:
rc = set(rossmore_crimes)
rc

{'ARSON',
 'ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT',
 'ATTEMPTED ROBBERY',
 'BATTERY - SIMPLE ASSAULT',
 'BATTERY WITH SEXUAL CONTACT',
 'BIKE - STOLEN',
 'BRANDISH WEAPON',
 'BUNCO, GRAND THEFT',
 'BURGLARY',
 'BURGLARY FROM VEHICLE',
 'BURGLARY, ATTEMPTED',
 'CHILD NEGLECT (SEE 300 W.I.C.)',
 'CRIMINAL THREATS - NO WEAPON DISPLAYED',
 'DISTURBING THE PEACE',
 'DOCUMENT FORGERY / STOLEN FELONY',
 'INTIMATE PARTNER - AGGRAVATED ASSAULT',
 'INTIMATE PARTNER - SIMPLE ASSAULT',
 'LETTERS, LEWD  -  TELEPHONE CALLS, LEWD',
 'OTHER ASSAULT',
 'PICKPOCKET',
 'RAPE, FORCIBLE',
 'ROBBERY',
 'SHOPLIFTING-GRAND THEFT ($950.01 & OVER)',
 'THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND OVER)',
 'THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)',
 'THEFT OF IDENTITY',
 'THEFT PLAIN - PETTY ($950 & UNDER)',
 'THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LIVESTK,PROD',
 'THREATENING PHONE CALLS/LETTERS',
 'TRESPASSING',
 'UNAUTHORIZED COMPUTER ACCESS',
 'VANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS)',
 'VANDALISM - MISDEAMEANOR ($399 OR UNDER)',
 'VEHICLE - STOLEN',
 'VIOLATION OF RESTRAINING ORDER'}